### ISSUE TITLE
Support --ignore-revs which uses a file with revisions listed (usually named .git-blame-ignore-revs)

### ISSUE THREAD

**Issue by z-aki** [frou/st3-gitblame#58]
Git blame added support for option `ignore-revs`. It would be great if this package can support this flag so that users can specify it in settings file and use the file which their projects provide.

**Comment by frou** [comment]
That sounds reasonable. Is it a universal enough convention that such a file is always at the root of the git repo?

**Comment by z-aki** [comment]
Thanks for the prompt response! 
Yes that's what I've seen in several GitHub repos. 
Also consider reading value from git config, since the file doesn't take effect until you set that option. Or pass it explicitly (which is painful).
See for example https://reviews.llvm.org/D67145

**Comment by frou** [comment]
After cloning some repo, I imagine hardly anyone either knows, or takes the time, to set the git config option?

If this package can find the file, I'd be inclined to be presumptuous and go ahead and use it. i.e. be opt-out rather than opt-in.

**Comment by z-aki** [comment]
Don't know about others, but we have mentioned it in developer documents. :) 
Opt-out is easy too. Add a command line option `--ignore-revs=""` which nullifies all previously parsed SHAs (whether from the file, or from command line).

**Comment by lswainemoore** [comment]
@frou is this actively in progress? i'd be willing to have a go at it if not.

**Comment by frou** [comment]
@lswainemoore Nope, IIRC I got a bit confused when thinking about it, because @z-aki's use case (where the user explicitly sets a git-config variable in a repo, presumably by running something like `git config --local --add blame.ignoreRevsFile .git-blame-ignore-revs`) already seems to influence this Sublime plugin fine without any changes required.

You're welcome to think about the different use cases and have a go at a new feature if it makes sense.

**Comment by lswainemoore** [comment]
oh nice! i actually hadn't tried it yet, so if that works, good enough for me. thanks!

**Comment by frou** [comment]
Just a brain dump:

There could be a new setting in this package called either `"auto_discover_ignorerevs_file"` (default `false`), or `"ignorerevs_file"` (default `""`). The latter would be more flexible since it's not guaranteed that such a file always uses the conventional `.git-blame-ignore-revs` name ([example](https://github.com/microsoft/accessibility-insights-web/blob/master/.ignoredRevs)). In either case the new setting should default to disabled, because by default I don't think this package should show different results than running plain git blame on the commandline does.

The file should be checked for relative to the root of the repo (discovered by calling `git rev-parse --show-toplevel`) and if it exists then `--ignore-revs-file /path/to/file` arguments should be added to calls to git.

We make use of the related `--ignore-rev SHA` option already as a way to build up state when pressing the `[Prev]` button to step back through commits in the UI.

**Comment by z-aki** [comment]
I filed the report because I had added the ignore rev command line option to the appropriate setting in preferences. And the plugin had some issues working after that. I'll try to redo it tomorrow.
