### ISSUE TITLE
How can I set the width of the left-hand column when I do the Ctrl + Shift + C (on Linux) view? (please don't shorten/hide stuff with `...`)

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [frou/st3-gitblame#59]
Notice how my name is shortened with `...`? I'd like that left-hand column wider so I can see it all. How can I do this? If I can't, can you please make that a setting or option somehow please? 

![image](https://user-images.githubusercontent.com/6842199/107871997-a852a580-6e5b-11eb-9f13-db54042ee690.png)

Currently I'll just stick to regular `git blame` opened up in Sublime Text with my `git blametool` script instead. Here's what that looks like when I run `git blametool useful_scripts/git-blametool.sh` at the command-line (you can see it also opens up in Sublime Text):

![image](https://user-images.githubusercontent.com/6842199/107872014-d0da9f80-6e5b-11eb-8b76-072da6ee9b2b.png)

I do think your tool is more convenient, however, if only it showed the whole name. But, when I need to see someone else's name, I really need to see their whole name, so unless you can expand that left-column more, your tool just doesn't meet my basic need of needing to see the whole `git blame` output.

**Comment by frou** [comment]
Yep, that's a valid point.

It does that because when there are multiple different names, they all have to be made the same fixed length so that the rest of the content in the lines will be aligned.

But obviously a more correct way to achieve the same goal is to detect the length of the longest name and right-pad the other names up to that length. I'll make that change in the next version.

**Comment by ElectricRCAircraftGuy** [comment]
> But obviously a more correct way to achieve the same goal is to detect the length of the longest name and pad out the other names up to that length. I'll make that change in the next version.

@frou, awesome. Thank you.

I've added your plugin to my list of plugins I'm evaluating: https://github.com/ElectricRCAircraftGuy/eRCaGuy_dotfiles/tree/master/Sublime_Text_editor (isn't on there now--will be pushed to that repo later).

One more thing: I'd like to be able to select and copy text from the git blame output, so I can easily copy the hash and check it out or look at its log at the command-line, for instance.

**Comment by frou** [comment]
Gabriel - this is implemented now (but not released yet since I'll be putting more than one change into the next version of this package)

<img width="832" alt="Screenshot 2021-02-20 at 14 29 24" src="https://user-images.githubusercontent.com/172663/108599408-d9196a00-7388-11eb-91ee-4f8d2db196dd.png">

---

> One more thing: **I'd like to be able to select and copy text from the git blame output**, so I can easily **copy the hash** and check it out or look at its log at the command-line, for instance.

As you probably know, that is already possible using the `Git Blame: Show` feature for single lines, by clicking the `[Copy]` button. It's probably not going to be possible for `Git Blame: Show All` because:
* Due to limitations of ST's API, I don't think it's possible to use normal click-and-drag mouse selection to highlight text in these "Phantoms".
* They could each have a clickable `[Copy]` button, but that makes an already wide thing even wider, and when we did experiment with that in the past, the existence of that extra button many times over seemed to cause major slowdown when scrolling medium-large files.

**Comment by frou** [comment]
The new version including this change was just released. I think it normally takes an hour or two to propagate to the PackageControl system.
